datadir: /data/CMIP6/MPI-ESM
server_prefix: http://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/CMIP
name: v_component_of_wind
cmip_name: va
era_name: v
output_type: 6hrPlevPt
run: r1i1p1f1
version: v20190815
res:
  - 1.40625
  # - 5.625