datadir: /data/CMIP6/TaiESM1
server_prefix: https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP
name: u_component_of_wind
cmip_name: ua
era_name: u
run: r1i1p1f1
res:
  - 1.40625
  # - 5.625
